INSERT INTO CATEGORY (NAME) VALUES ('Informática');
INSERT INTO CATEGORY (NAME) VALUES ('Escritório');

INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Computador', 2000.00);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Impressora', 850.00);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Mouse', 80.00);

INSERT INTO PRODUCT_CATEGORY (ID_PRODUCT, ID_CATEGORY) VALUES (1, 1);
INSERT INTO PRODUCT_CATEGORY (ID_PRODUCT, ID_CATEGORY) VALUES (2, 1);
INSERT INTO PRODUCT_CATEGORY (ID_PRODUCT, ID_CATEGORY) VALUES (3, 1);

INSERT INTO PRODUCT_CATEGORY (ID_PRODUCT, ID_CATEGORY) VALUES (2, 2);

INSERT INTO CITY (NAME, STATE) VALUES ('Curitiba', 17);
INSERT INTO CITY (NAME, STATE) VALUES ('Campinas', 25);
INSERT INTO CITY (NAME, STATE) VALUES ('Itajai', 23);

INSERT INTO CLIENT (NAME, EMAIL, CPF_OR_CNPJ, TYPE) VALUES ('Bruno Henrique Costa', 'bruno@gmail.com', '36985214789', 0);

INSERT INTO PHONE (CLIENT_ID_CLIENT, PHONES) VALUES (1, '43988147788');
INSERT INTO PHONE (CLIENT_ID_CLIENT, PHONES) VALUES (1, '41966332211');

INSERT INTO ADDRESS (ID_CITY, ID_CLIENT, COMPLEMENT, NEIGHBORHOOD, NUMBER, STREET, ZIP_CODE) VALUES (1, 1, 'Casa', 'Pinheirinho', 985, 'Rua 7 de setembro', '81870-000');
INSERT INTO ADDRESS (ID_CITY, ID_CLIENT, COMPLEMENT, NEIGHBORHOOD, NUMBER, STREET, ZIP_CODE) VALUES (3, 1, 'Apartamento 206', 'Praia Brava', 1256, 'Rua Mariano torres', '96587-000');


